### ISSUE TITLE
Our app using update-notifier is crashing for a lot of our users

### ISSUE THREAD

**Issue by LinusU** [yeoman/update-notifier#76] opened 2016-04-27 21:04 UTC
Original issue: tessel/t2-cli#714

We have quite a few users that are getting crashes because they don't have permissions to write to the config file used. Unfortunately, I'm not sure exactly why this happens, and I'm not even sure how this should be handled, but I thought it was a good idea to open this ticket to get some thoughts.

On the one hand, the behaviour could be considered correct. But on the other hand, it might be a good idea to fail gracefully since this is more of an advisory tool.

I've confirmed that wrapping the call to update notifier in a try/catch correctly catches the problem, so that is one way of dealing with it from our side.

**Comment by nexdrew** [comment] 2016-04-28 14:56
FWIW, I recently encountered this problem as well, see https://github.com/npm/npme-installer/pull/132 for my workaround.

In my case, the problem is caused by the fact that I was running `update-notifiier` as part of the standard bin which is executed as a `postinstall` script, and we advise folks to install as sudo. This resulted in the `~/.config/configstore/update-notifier-npme.json` file belonging to the root user even though it's in the current user's home directory, and subsequent bin executions by without sudo would always cause `update-notifier` (and thus the bin) to crash.

I agree with @LinusU that perhaps this is a consumer problem (and can confirm that wrapping in try/catch works since the fs operations are synchronous), but failing gracefully on fs permission errors would be nice. Maybe notify on process exit with a friendly error message stating that the update check failed?

**Comment by jephir** [comment] 2016-04-28 17:08
Getting a similar issue here. My app is running as **nobody** user for security reasons and has no home directory. `update-notifier` then crashes the app.

```
 Error: EACCES: permission denied, mkdir '/nonexistent'
     at Error (native)
     at Object.fs.mkdirSync (fs.js:916:18)
     at sync (/usr/src/app/node_modules/mkdirp/index.js:71:13)
     at sync (/usr/src/app/node_modules/mkdirp/index.js:77:24)
     at Function.sync (/usr/src/app/node_modules/mkdirp/index.js:77:24)
     at Object.create.all.get (/usr/src/app/node_modules/configstore/index.js:41:13)
     at Object.Configstore (/usr/src/app/node_modules/configstore/index.js:27:44)
     at new UpdateNotifier (/usr/src/app/node_modules/update-notifier/index.js:33:17)
     at module.exports (/usr/src/app/node_modules/update-notifier/index.js:126:23)
     at Object.<anonymous> (/usr/src/app/node_modules/superstatic/bin/server:20:16)

```

**Comment by sindresorhus** [comment] 2016-04-28 18:42
> but failing gracefully on fs permission errors would be nice. Maybe notify on process exit with a friendly error message stating that the update check failed?

Agreed. That would be much better. I would merge a PR adding pretty much exactly what you did in https://github.com/npm/npme-installer/pull/132#issuecomment-215475097.

**Comment by sindresorhus** [comment] 2016-04-28 18:46
Still, I would prefer to fix the actual problem. I refuse to believe that so many people have permission problems. There has to be something else going on. Maybe having everything in one `configstore` directory was a bad idea? Currently, any tool can ruin the permissions for everyone. Maybe we should instead create individual directories for each consumer? `~/.config/configstore-update-notifier-npme/config.json`?

**Comment by sindresorhus** [comment] 2016-04-28 18:47
> Getting a similar issue here. My app is running as nobody user for security reasons and has no home directory. update-notifier then crashes the app.

You don't even have a tempdir? `configstore` [falls back to](https://github.com/yeoman/configstore/blob/a4692d4f0c5aad76b29a770f3dbda2575e303fe0/index.js#L14) the system tempdir when there's no homedir.

**Comment by nexdrew** [comment] 2016-04-28 18:48
@sindresorhus Cool thanks, I can put something together and then you can decide to use it or not.

Note that I found it necessary to chown the whole directory recursively instead of just chown'ing the one file. This is reflected here: https://github.com/npm/npme-installer/pull/134

Not sure which would be better. Note that other tools like git store config in `~/.config` as well, but I would think chown'ing it to the current user should be safe (?).

**Comment by sindresorhus** [comment] 2016-04-28 18:50
// @SBoudrias @sheerun @Qix-

**Comment by sindresorhus** [comment] 2016-05-05 06:57
I wouldn't consider this solved, just worked around for now. I'd like to see a real solution at some point.

**Comment by jimbojw** [comment] 2016-05-16 09:44
The root cause of this issue is a bug in `write-file-atomic` which is used by `configstore`. I have documented it here: https://github.com/npm/write-file-atomic/issues/11

In short, write-file-atomic creates a new temporary file, writes the desired content, optionally updates ownership and permissions, and then overwrites the target file. In so doing, the new file will have the owner/group and umask of the user running the command by default.

So when you run something that touches configstore through sudo, the temp file is created belonging to root, with permissions rw-r--r-- (644). Then when this file overwrites the original, its ownership  and permissions are clobbered.

**Comment by sindresorhus** [comment] 2016-06-15 12:44
@jimbojw Thanks for looking into that. Makes sense. Could you or anyone in this thread do a PR on `write-file-atomic` or just write a better module? (I've had other problems with that module in the past that went unsolved).

**Comment by Qix-** [comment] 2016-06-15 20:45
Looks to be a bug, not a feature FWIW. Shouldn't be chowning anything programmatically unless you have a really good reason to.

**Comment by sindresorhus** [comment] 2016-06-16 09:51
@sheerun did a pull request 👏 https://github.com/npm/write-file-atomic/pull/13

**Comment by sheerun** [comment] 2016-09-01 11:41
@sindresorhus Write-file-atomic has beed released with fix. Do you want to release update-notifier?

**Comment by kevva** [comment] 2016-09-06 23:59
@sheerun, no need to. It was just a minor release. Going to close as this should be resolved now.

**Closed by kevva** 2016-09-06 23:59 UTC
