### ISSUE TITLE
Add support for private registry 

### ISSUE THREAD

**Issue by jacinzhang** [yeoman/update-notifier#149] opened 2019-02-21 09:22 UTC
It seems `update-notifier` check version update info only from `https://registry.npmjs.org/`, can it support check private registry?

**Comment by adoyle-h** [comment] 2019-03-19 08:22
Not fixed yet. #100

**Comment by sindresorhus** [comment] 2019-03-28 11:41
Duplicate of #100

**Closed by sindresorhus** 2019-03-28 11:41 UTC
